{
  "id":8,
  "name":"mghcategories",
  "formtabs":[
    {
      "MIGX_id":14,
      "caption":"Element",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":38,
          "field":"package",
          "caption":"Package",
          "description":"Package Name, which the Element belongs to. Saves to the package - path.",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"",
          "validation":"",
          "configs":"",
          "restrictive_condition":"",
          "display":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":"",
          "pos":1
        }
      ],
      "pos":1
    }
  ],
  "contextmenus":"",
  "actionbuttons":"loadElements",
  "columnbuttons":"update||writeElFiles",
  "filters":[
    {
      "MIGX_id":1,
      "name":"category",
      "label":"category",
      "emptytext":"Search...",
      "type":"textbox",
      "getlistwhere":{
        "Element.category:LIKE":"%[[+category]]%"
      },
      "getcomboprocessor":"",
      "combotextfield":"",
      "comboidfield":"",
      "comboparent":"",
      "default":""
    }
  ],
  "extended":{
    "migx_add":"Add Category",
    "disable_add_item":"",
    "add_items_directly":"",
    "formcaption":"",
    "update_win_title":"",
    "win_id":"memcategories",
    "maxRecords":"",
    "addNewItemAt":"bottom",
    "media_source_id":"",
    "multiple_formtabs":"",
    "multiple_formtabs_label":"",
    "multiple_formtabs_field":"",
    "multiple_formtabs_optionstext":"",
    "multiple_formtabs_optionsvalue":"",
    "actionbuttonsperrow":4,
    "winbuttonslist":"",
    "extrahandlers":"",
    "filtersperrow":4,
    "packageName":"migxgpmhelper",
    "classname":"mghCategory",
    "task":"",
    "getlistsort":"",
    "getlistsortdir":"",
    "sortconfig":"",
    "gridpagesize":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"",
    "has_jointable":"no",
    "getlistwhere":"",
    "joins":[
      {
        "alias":"Element"
      }
    ],
    "hooksnippets":"",
    "cmpmaincaption":"Elements Manager",
    "cmptabcaption":"Categories",
    "cmptabdescription":"Manage Elements here",
    "cmptabcontroller":"",
    "winbuttons":"",
    "onsubmitsuccess":"",
    "submitparams":""
  },
  "columns":[
    {
      "MIGX_id":1,
      "header":"ID",
      "dataIndex":"id",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderchunktpl":"",
      "renderoptions":""
    },
    {
      "MIGX_id":2,
      "header":"Name",
      "dataIndex":"Element_category",
      "width":30,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderRowActions",
      "clickaction":"",
      "selectorconfig":"",
      "renderchunktpl":"",
      "renderoptions":""
    }
  ],
  "createdby":1,
  "createdon":"2020-05-10 20:10:10",
  "editedby":1,
  "editedon":"2020-05-10 20:35:35",
  "deleted":0,
  "deletedon":null,
  "deletedby":0,
  "published":1,
  "publishedon":null,
  "publishedby":0,
  "category":""
}